feat: remove runtime dependency on api key by using token provider
Stedi-Demos/integrations-sdk pull request #125
Opened 2023-07-21 18:57 UTC by rsioss

2023-07-21 18:59 UTC, rsioss commented on src/common/constants.ts
> +interface ClientConfig {
added this interface to appease eslint (it didn't like the inferred type of `DEFAULT_SDK_CLIENT_PROPS` below after adding the `...credentials` destructuring)

2023-07-21 18:59 UTC, rsioss commented on src/deploy/deploy-resources.ts
> -  const FUNCTION_NAMES: string[] = [];
had an IDE warning for this... the value is set but never read

2023-08-01 12:53 UTC, BDQ approved these changes

2023-08-02 12:58 UTC, OlafConijn requested changes
please hold of mergning untill we have an updated version of the `@stedi/sdk-token-provider-aws-identity` lib

2023-08-04 17:26 UTC, OlafConijn approved these changes
approved. there found a solution around having to update the client SDKs. all good, apologies for the churn.

2023-08-04 17:35 UTC, merged